name: tizona
on:
  pull_request:
  push:

jobs:
  security_check_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Security check 
        uses: empathyco/tizona-action@pre-v1
        with:
          deptrack_enable: 'false'
          code_enable: 'false'
          secrets_enable: 'false'
          reviewdog_github_token: ${{ secrets.github_token }}
          reviewdog_working_directory: 'terraform'
          reviewdog_level: 'info'
          reviewdog_reporter: 'github-pr-review'
          trivy_config_severity: 'CRITICAL,HIGH'
          trivy_repo_ignore-unfixed: 'true'
          trivy_repo_severity: 'CRITICAL,HIGH'
          trivy_timeout: '15m'